.TH "OSSVOL" "1" "April 2009" "" ""
.SH "NAME"
ossvol \- a simple volume manager for oss

.SH "SYNOPSIS"
ossvol [option] [argument]
.SH "DESCRIPTION"
OSSVol is a simple volume management script for OSS (Open Sound System). OSSVol was written to add support for a rather painful oversight \- the OSS default volume manager (ossmix) lacks the ability to mute!
.SH "OPTIONS"
.TP 
\fB\-i\fR, \fB\-\-increase\fR
Increase volume by [argument]
.TP 
\fB\-d\fR, \fB\-\-decrease\fR
Decrease volume by [argument]
.TP 
\fB\-t\fR, \fB\-\-toggle\fR
Toggle mute on and off
.TP 
\fB\-h\fR, \fB\-\-help\fR
Display help
.SH "AUTHORS"
Ghost1227
